### ISSUE TITLE
free-ada fails to compile for "native" (x86_64)

### ISSUE THREAD

**Issue by jcdubois** [Lucretia/free-ada#3]
I tried to compile "free-ada" for native (x86_64 on Ubuntu 17.10) but gcc 6.4 fails to compile.

Here are the log files generated during the compilation.

[gcc-6.4.0-config.txt](https://github.com/Lucretia/free-ada/files/1584875/gcc-6.4.0-config.txt)
[gcc-6.4.0-make.txt](https://github.com/Lucretia/free-ada/files/1584876/gcc-6.4.0-make.txt)

Note that compilation is succeeding when compiling for "cross compilation" (ARM, MIPS, AVR, LEON, ...)

**Comment by Lucretia** [comment]
Looks like you don't have your kernel headers or system dev installed. You need to install on ubuntu the dev base stuff, I can't remember what the correct command line is. Also make sure you install the gcc [prerequisites for testing](https://gcc.gnu.org/install/prerequisites.html) as well.

**Comment by jcdubois** [comment]
I do have the system/kernel headers installed.

As a matter of fact the "missing" file /usr/include/x86_64-linux-gnu/asm/errno.h is preset on my system.

But the generated "xgcc" compiler doesn't seems to have the /usr/include/x86_64-linux-gnu as a directory to search for headers.

Would it be looking in /usr/include/x86_64-pc-linux-gnu instead?
