### ISSUE TITLE
MPFR shoud move to 3.1.6

### ISSUE THREAD

**Issue by jcdubois** [Lucretia/free-ada#4]
The MPFR version on http://mpfr.loria.fr/mpfr-current is 3.1.6

3.1.5 is failing to download.

diff --git a/config-master.inc b/config-master.inc
index 33ccd90..8dd45f5 100644
--- a/config-master.inc
+++ b/config-master.inc
@@ -197,7 +197,7 @@ export MPC_DIR=mpc-$MPC_VERSION
 #export MPFR_MIRROR=http://www.mpfr.org/mpfr-$MPFR_VERSION
 #export MPFR_PATCHES=http://www.mpfr.org/mpfr-$MPFR_VERSION/allpatches
 #export MPFR_VERSION=3.1.2
-export MPFR_VERSION=3.1.5
+export MPFR_VERSION=3.1.6
 export MPFR_MIRROR=http://mpfr.loria.fr/mpfr-current
 export MPFR_PATCHES=http://mpfr.loria.fr/mpfr-current/allpatches
 export MPFR_TARBALL=mpfr-$MPFR_VERSION.tar.xz

**Comment by jcdubois** [comment]
Actually the patch from Robert Roland seems a better one.

https://github.com/robdaemon/free-ada/commit/64e94822dca7faff8f2acb6152f6f8a0ef640390

**Comment by Lucretia** [comment]
Bumped version.
