### ISSUE TITLE
Default MPC mirror in config.inc.sh is no longer valid.

### ISSUE THREAD

**Issue by Rodeo-McCabe** [Lucretia/free-ada#8]
The links on the MPC download page now point to https://ftp.gnu.org/gnu/mpc/

Replacing MPC_MIRROR (line 183 of config.inc.sh) with that value fixes the download.

**Comment by Rodeo-McCabe** [comment]
The pull request by kalkin fixes this problem and others.

**Comment by Lucretia** [comment]
Fixed with current gcc-9.x branch.
